### ISSUE TITLE
Compile error / inaccurate version bounds

### ISSUE THREAD

**Issue by hvr** [rodrigosetti/messagepack#11]
Hi,

The latest release of `messagepack` fails to build with GHC 7.4:

```
Configuring component lib from messagepack-0.5.4
Preprocessing library messagepack-0.5.4...

Data/MessagePack.hs:22:8:
    Could not find module `GHC.Generics'
    It is a member of the hidden package `ghc-prim'.
    Perhaps you need to add `ghc-prim' to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

Moreoever, when depending on `deepseq` you should use version bounds as well, as e.g. deepseq-1.0 had a totally different API that has *nothing* in common with all that came after; also, with deepseq-1.4 I switched the default method implementation of `rnf` in a subtle but dangerous way which could easily result in silent breakage. And when I release `deepseq-1.5` it will at the very least remove one or two instances, and there's also the risk that some semantics may be changed. long story short: I recommend using `deepseq >= 1.1 && <1.5` to be on the safe side.

Finally, `messagepack` appears to have started using `Generics` and `DeriveGeneric`; you should declare `other-extensions: DeriveGeneric` so that the cabal solver knows that a compiler is needed which supports that extension (e.g. GHC 7.0 didn't support generics yet)

**Comment by hvr** [comment]
Fyi, I've revised the meta-data on Hackage, see https://hackage.haskell.org/package/messagepack-0.5.4/revisions/

**Comment by rodrigosetti** [comment]
Thanks for changing in Hackage - will update the cabal file
