### ISSUE TITLE
Add package to stackage again

### ISSUE THREAD

**Issue by saep** [rodrigosetti/messagepack#13]
Can you make a release which contains the changes of #12 ? A few of my packages depend on this package and I would like to add them to stackage again.
I wouldn't mind doing these simple maintenance tasks myself if you give me the rights for it.

**Comment by rodrigosetti** [comment]
Updated cabal metadata for messagepack-0.5.4

What is your hackage username?

**Comment by saep** [comment]
My hackage username is [saep](http://hackage.haskell.org/user/saep). Thanks for updating the metadata.

**Comment by rodrigosetti** [comment]
No problem. Added you as maintainer in Hackage.
