### ISSUE TITLE
test-suite build failure in stackage nightly

### ISSUE THREAD

**Issue by bergmark** [rodrigosetti/messagepack#9]
```
tests/Main.hs:36:10:
    Duplicate instance declarations:
      instance (Ord k, Arbitrary k, Arbitrary v) => Arbitrary (M.Map k v)
        -- Defined at tests/Main.hs:36:10
      instance [safe] (Ord k, Arbitrary k, Arbitrary v) =>
                      Arbitrary (M.Map k v)
        -- Defined in ‘Test.QuickCheck.Arbitrary’
```

**Comment by bergmark** [comment]
The test-suite for this package has been disabled in stackage because of this issue. When a fix is published to hackage could you please send a PR to re-enable the tests to stackage (it's in the skipped-tests section) or ping me?

Thanks!

**Comment by rodrigosetti** [comment]
pushed the new version to hackage: http://hackage.haskell.org/package/messagepack-0.5.3
